magento_integration/magento_integration/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.conf.urls import url
router = DefaultRouter()

urlpatterns = [

    url('', include('magento_integration_app.urls')),
    path('admin/', admin.site.urls),
]

magento_integration/magento_integration_app/urls.py
from django.urls import path
from .views import ApiOverview,RegistrationView,LoginView,ProductListView,ProductDetailView,\
    AddToCartView,CartView,CartItemView,CartItemDetailView,DashboardView,ProductView,ProductDetailView_1,\
    get_cart_items,get_cart_item,create_cart_item,update_cart_item,delete_items,\
    CustomUserView,CustomUserDetailView,\
    CustomerView,CustomerDetailView,\
    CartView,CartDetailView,CartItem,BaseView
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'magento_integration_app'

urlpatterns = [
    #url crud w drf'ie dla produktow
    path('products/items/', ProductView.as_view(), name='products'),
    path('products/items/get/<str:magento_sku>/', ProductView.as_view(), name='products-item'),
    path('products/items/update/<str:magento_sku>/', ProductDetailView_1.as_view(), name='update-product'),
    path('products/items/delete/<str:magento_sku>/', ProductDetailView_1.as_view(), name='delete-product'),

    #url crud w drf'ie dla modelu CustomUser(klasyfikacja, przydzielanie uprawnien zgodnie z grupa)
    path('user/permission/', CustomUserView.as_view(), name='users_permission'),
    path('user/permission/get/<int:id>/', CustomUserView.as_view(), name='user_permission'),
    path('user/permission/update/<int:id>/', CustomUserDetailView.as_view(), name='update-user_permission'),
    path('user/permission/delete/<int:id>/', CustomUserDetailView.as_view(), name='delete-user_permission'),

    #url crud w drf'ie dla modelu Customer
    path('customer/customers/', CustomerView.as_view(), name='customers'),
    path('customer/customers/get/<str:magento_sku>/', CustomerView.as_view(), name='customer'),
    path('customer/customers/update/<str:magento_sku>/', CustomerDetailView.as_view(), name='update-customer'),
    path('customer/customers/delete/<str:magento_sku>/', CustomerDetailView.as_view(), name='delete-customer'),

    #url rejestracja oraz logowanie
    path('api/register/', RegistrationView.as_view(), name='api-register'),
    path('api/login/', LoginView.as_view(), name='api-login'),

    #widoki pomocnicze(tesotwanie)
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    #dodwanie produktu do koszyka
    path('add_to_cart/', AddToCartView.as_view(), name='add-to-cart'),

    #url crud w drf'ie dla modelu Cart
    path('cart/items/', CartView.as_view(), name='carts'),
    path('cart/items/get/<int:customer_id>/', CartView.as_view(), name='cart'),
    path('cart/items/update/<int:cart_id>/', CartDetailView.as_view(), name='update-cart'),
    path('cart/items/delete/<int:cart_id>/', CartDetailView.as_view(), name='delete-cart'),


    #url crud w drf'ie dla modelu CartItem
    path('cart_item/items/', CartItemView.as_view(), name='cart-items'),
    path('cart_items/items/get/<int:cart_id>/', CartItemView.as_view(), name='cart-item'),
    path('cart_items/items/update/<int:cart_id>/', CartItemDetailView.as_view(), name='update-cart-item'),
    path('cart_items/items/delete/<int:cart_id>/', CartItemDetailView.as_view(), name='delete-cart-item'),

    #url zastepcze, crud w drf'ie opraty na funkcjach
    path('cart/items2/', get_cart_items, name='get-cart-items'),
    path('cart/items2/<int:item_id>/', get_cart_item, name='f_get-cart-item'),
    path('cart/items2/create/', create_cart_item, name='f_create-cart-item'),
    path('cart/items2/update/<int:id>/', update_cart_item, name='f_update-cart-item'),
    path('cart/items2/delete/<int:id>/', delete_items, name='f_delete-cart-item'),

    #ogolny panel api
    #widoki odpowiadajace za uwierzytelnienie api
    #widok dashboarda -test wykresow
    path('api/panel/', ApiOverview, name='home'),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('', BaseView.as_view(), name='base'),

]

magento_integration/magento_integration_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission,User
from django.contrib.sessions.models import Session

#model przydzielania uprawnien, uzytkownikowi
class CustomUser(AbstractUser):
    groups = models.ManyToManyField(Group, related_name='customuser_set')
    user_permissions = models.ManyToManyField(Permission, related_name='customuser_set')

#model przechowujacy dane klienta zarejestrowanego(oczywiście do rozwinięcia)
class Customer(models.Model):
    magento_sku = models.CharField(max_length=100, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_deleted = models.DateTimeField(null=True, blank=True)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)
    is_subscribed = models.BooleanField(default=False)

    # Zwracane pole, które uważasz za ważne

    def __str__(self):
        return self.magento_sku

#model Kategorii danego produktu znajdującego sie w sklepie
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# model produktu i atrybutu z nim związane
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    magento_sku = models.CharField(max_length=100)
    size = models.CharField(max_length=50)
    available = models.BooleanField(default=True)
    stock_quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.name
#funkcja sprawdzajaca dostepnosc produktu
    def update_availability(self):
        self.available = self.stock_quantity > 0
        self.save()

#model Koszyka powiązany z klientem, produktami i sesja
# (do obsłuzenia, w tym momencie po wyczerpaniu czasu zdefiniowanego w settingsach przy użyciu firebase'a,
# uzytkownik zostaje wylogowany z platoformy, a trzeba zmienic to na usuwanie automatyczne produktów
# z koszyka)
class Cart(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')
    session = models.ForeignKey(Session, null=True, blank=True, on_delete=models.SET_NULL)

#funkcja obliczajaca sume produktow znajdujacych sie w koszyku klienta, zgodnie z iloscia danego produktu i jego ceny

    def calculate_total_price(self):
        total_price = 0
        cart_items = CartItem.objects.filter(cart=self)
        for item in cart_items:
            total_price += item.product.price * item.quantity
        return total_price

    def __str__(self):
        return f"Cart - {self.customer.user.username} - {self.calculate_total_price()}"
#model odpowiadajacy za produkty dodane do koszyka)
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"CartItem - {self.product.name} - Quantity: {self.quantity}"

magento_integration/magento_integration_app/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework import status,generics
from django.contrib.auth import authenticate, login, logout
from .serializers import UserSerializer ,ProductSerializer,CartItemSerializer,CustomUserSerializer,CustomerSerializer,CartSerializer
from django.utils.crypto import get_random_string
from .models import Customer,Product,Cart,CartItem,CustomUser
from django.contrib import messages
from django.http import JsonResponse
from django_filters.rest_framework import DjangoFilterBackend
from django_tables2.views import SingleTableView
from .tables import ProductTable
from django.contrib.sessions.models import Session
from django.utils import timezone
from rest_framework.decorators import api_view, permission_classes,authentication_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from rest_framework.authentication import SessionAuthentication
import json



#widok testowy dashboarda'a, wykresy itd
class DashboardView(TemplateView):
    template_name = 'dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Pobierz dane dotyczące ilości produktów z magazynu
        stock_data = Product.objects.values('name', 'stock_quantity')

        context['stock_data_json'] = json.dumps(list(stock_data))
        return context



#widok ogolny api, z informacjami o wszystkich url i dostepu do nich
@api_view(['GET'])
def ApiOverview(request):
    api_urls = {
        'get_all_from_custom_user': 'custom_user/get_many_user/',
        'get_all_items_from_cart': 'cart/get_many_items',
        'get_one_item_from_cart' : 'cart/get_item/<int:item_id>/',
        'add_item_to_cart': 'add_to_cart/',
        'create_item': 'cart/post/',
        'update_item_in_cart': 'cart/put/<int:item_id>/',
        'delete_item_in_cart': 'remove-from-cart/<int:item_id>/'
    }

    return Response(api_urls)

#widok zwracajacy wszystkie produkty
class ProductListView(generics.ListAPIView):
    serializer_class = ProductSerializer
    def get_queryset(self):
        queryset = Product.objects.all()

        # Jeśli przekazane jest Magento SKU w parametrze żądania
        magento_sku = self.request.query_params.get('magento_sku')
        if magento_sku:
            queryset = queryset.filter(magento_sku=magento_sku)

        return queryset
    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)

        # Renderowanie szablonu
        return render(request, 'product_list.html', {'products': serializer.data})

#widok odpowiadajacy za szczegoly interesujacego nas produktu
class ProductDetailView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    template_name = 'product_detail.html'

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return render(request, self.template_name, {'product': serializer.data})

# widok dodawania produktow do koszyka
class AddToCartView(generics.CreateAPIView):
    queryset = Cart.objects.all()
    serializer_class = CartItemSerializer

    def post(self, request, *args, **kwargs):
        product_magento_sku = request.data.get('magento_sku')
        quantity = request.data.get('quantity')

        if not product_magento_sku:
            return Response({'error': 'Pole "magento_sku" jest wymagane.'}, status=status.HTTP_400_BAD_REQUEST)
        if not quantity:
            return Response({'error': 'Pole "quantity" jest wymagane.'}, status=status.HTTP_400_BAD_REQUEST)

        # Sprawdzenie, czy produkt istnieje
        try:
            product = Product.objects.get(magento_sku=product_magento_sku)
        except Product.DoesNotExist:
            return Response({'error': 'Podany produkt nie istnieje.'}, status=status.HTTP_400_BAD_REQUEST)

        # Sprawdzenie, czy ilość produktu w magazynie nie wynosi zero
        if product.stock_quantity == 0:
            return Response({'error': 'Wybranego produktu nie ma w magazynie.'}, status=status.HTTP_400_BAD_REQUEST)

        # Sprawdzenie, czy istnieje aktywna sesja
        session_key = request.session.session_key
        if not session_key:
            # Twórz nową sesję
            request.session.create()
            session_key = request.session.session_key

        # Sprawdzenie, czy istnieje koszyk powiązany z daną sesją i klientem
        customer = Customer.objects.get(user=request.user)
        cart, created = Cart.objects.get_or_create(customer=customer, session_id=session_key)

        # Dodawanie produktu do koszyka
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)

        # Zaktualizowanie ilości produktu w koszyku
        cart_item.quantity += int(quantity)
        cart_item.save()

        return Response({'success': 'Produkt został dodany do koszyka.'}, status=status.HTTP_201_CREATED)

class RegistrationView(APIView):
    def get(self,request):
        return render(request,'register.html')

    def post(self, request):
        print(request.data)
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            try:
                customer = Customer.objects.get_object_or_create(user=user, magento_sku=get_random_string(length=10))
                messages.success(request, 'Konto zostało poprawnie utworzone. Możesz się teraz zalogować.')
                return JsonResponse({'success': True, 'message': 'Konto zostało poprawnie utworzone.'})
            except Exception as e:
                return Response(str(e), status=status.HTTP_400_BAD_REQUEST)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#widok do logowania(jeszcze trzeba dodac poprawki, na szybko)
class LoginView(APIView):
    def get(self,request):
        return render(request,'login.html')
    def post(self, request):
        username = request.data.get('username')
        password = request.data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            token, created = Token.objects.get_or_create(user=user)
            return Response({'token': token.key}, status=status.HTTP_200_OK)
        return Response({'error': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)

#widok do wylogowania
class LogoutView(APIView):
    def post(self, request):
        logout(request)
        return Response(status=status.HTTP_200_OK)

#widok koszyka danego klienta oraz produktow, ktore do niego dodal


class CartView(generics.ListCreateAPIView):
    serializer_class = CartSerializer

    def get_queryset(self):
        customer_id = self.kwargs.get('customer_id')

        if customer_id:
            return Cart.objects.filter(customer__magento_sku=customer_id)
        else:
            return Cart.objects.all()

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)

        # Renderowanie szablonu
        return render(request, 'cart.html', {'cart_items': serializer.data})


class CartDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer
    lookup_field = 'cart_id'


"""CRUD metoda oparta na klasach
pojedynczy klient,
wielu klientów,
dodawanie nowego klienta
GET,POST"""
class CustomerView(generics.ListCreateAPIView):
    serializer_class = CustomerSerializer

    def get_queryset(self):
        magento_sku = self.kwargs.get('magento_sku')
        if magento_sku:
            return Customer.objects.filter(magento_sku=magento_sku)
        else:
            return Customer.objects.all()

"""Aktualizacja klienta,
Usuwanie kleinta, z wykorzystaniem pola CARD_ID
PUT, RETRIVE,PATCH"""
class CustomerDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer
    lookup_field = 'magento_sku'

"""CRUD metoda oparta na klasach
pojedynczy produkt,
wiele produktów,
dodawanie nowego produktu
GET,POST"""

class ProductView(generics.ListCreateAPIView):

    serializer_class = ProductSerializer
    def get_queryset(self):
        magento_sku = self.kwargs.get('magento_sku')
        if magento_sku:
            return Product.objects.filter(magento_sku=magento_sku)
        else:
            return Product.objects.all()


"""Aktualizacja produktu,
Usuwanie produktu, z wykorzystaniem pola MAGENTO_SKU
PUT, RETRIVE,PATCH"""
class ProductDetailView_1(generics.RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'magento_sku'






"""CRUD metoda oparta na klasach
pojedynczy obiekt_w_koszyku,
wiele obiektów,
dodawanie nowego obiektu
GET,POST"""
class CartItemView(generics.ListCreateAPIView):
    serializer_class = CartItemSerializer

    def get_queryset(self):
        cart_id = self.kwargs.get('cart_id')
        print(cart_id)
        if cart_id:
            return CartItem.objects.filter(id=cart_id)
        else:
            return CartItem.objects.all()


"""Aktualizacja obiektu,
Usuwanie obiektu, z wykorzystaniem pola CARD_ID
PUT, RETRIVE,PATCH"""
class CartItemDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = CartItem.objects.all()
    serializer_class = CartItemSerializer
    lookup_field = 'cart_id'

magento_integration/magento_integration_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load navbar_tags %}

{% head %}

<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Twój Sklep</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Kategorie
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Kategoria 1</a>
            <a class="dropdown-item" href="#">Kategoria 2</a>
            <a class="dropdown-item" href="#">Kategoria 3</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Oferty</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'magento_integration_app:cart' request.user.customer %}">Koszyk</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Zalogowany użytkownik: {{ request_user }}</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

</body>

</html>

magento_integration/magento_integration_app/templates/cart.html
{% include 'base.html' with request_user=request.user %}
{% block content %}
  <div class="container">
    <h1>Koszyk</h1>
    <p><strong>Suma produktów:</strong> {{ total_price }}</p>
    <table class="table">
      <thead>
        <tr>
          <th>Nazwa</th>
          <th>Cena</th>
          <th>Ilość</th>
          <th>Usuń</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart_items %}
          <tr>
            <td>{{ item.product_name }}</td>
            <td>{{ item.product_price }}</td>
            <td>{{ item.quantity }}</td>
            <td>
              <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#removeFromCartModal{{ item.id }}" onclick="confirmRemoveFromCart({{ item.id }})">Usuń</button>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  {% for item in cart_items %}
    <div class="modal fade" id="removeFromCartModal{{ item.id }}" tabindex="-1" aria-labelledby="removeFromCartModalLabel{{ item.id }}" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="removeFromCartModalLabel{{ item.id }}">Usuwanie produktu z koszyka</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Czy na pewno chcesz usunąć ten produkt z koszyka?</p>
          </div>
          <div class="modal-footer">
            <form action="{% url 'magento_integration_app:delete-cart-item' cart_id=item.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Usuń</button>
            </form>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuluj</button>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
  <script>
  function confirmRemoveFromCart(itemId) {
    console.log(itemId);

    // Wywołaj widok usuwania i przekaż identyfikator produktu
    $.ajax({
      url: `/cart_items/items/delete/${itemId}/`,
      type: 'DELETE',
      headers: {
        'X-CSRFToken': '{{ csrf_token }}'
      },
      success: function(response) {
        // Jeśli usuwanie powiodło się
        $('#removeFromCartModal' + itemId).modal('hide'); // Schowaj modal
        location.reload(); // Odśwież stronę
      },
      error: function(xhr, status, error) {
        // Jeśli wystąpił błąd, wyświetl komunikat
        alert('Wystąpił błąd podczas usuwania produktu z koszyka.');
      }
    });
  }
</script>

{% endblock %}

magento_integration/magento_integration_app/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Logowanie</title>
    <style>
        /* Stylizacja w ciemnym motywie */
        body {
            background-color: #121212;
            color: #ffffff;
            font-family: Arial, sans-serif;
        }

        .container {
            width: 300px;
            margin: 0 auto;
            margin-top: 100px;
            padding: 20px;
            background-color: #1e1e1e;
            border-radius: 5px;
        }

        .form-group {
            margin-bottom: 10px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
        }

        .form-group input {
            width: 100%;
            padding: 5px;
            border: 1px solid #666666;
            border-radius: 3px;
            background-color: #ffffff;
            color: #000000;
        }

        .form-group button {
            padding: 5px 10px;
            background-color: #ffffff;
            color: #000000;
            border: none;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Logowanie</h2>
        <form id="login-form">
            <div class="form-group">
                <label for="email">Adres e-mail:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Hasło:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <button type="submit">Zaloguj się</button>
            </div>
        </form>
    </div>
</body>
    <script>
        // Logika formularza logowania
        document.getElementById("login-form").addEventListener("submit", function(event) {
            event.preventDefault();

            var formData = new FormData(this);
            var email = formData.get("email");
            var password = formData.get("password");

            // Wywołanie odpowiedniego API za pomocą DRF (np. za pomocą fetch lub axios)
            // Przetworzenie odpowiedzi i obsługa logiki logowania
        });
    </script>

</html>

magento_integration/magento_integration_app/templates/product_detail.html
<!-- product_list.html -->
{% include 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
      </div>
      <div class="col-md-8">
        <h1>{{ product.name }}</h1>
        <p class="lead">{{ product.description }}</p>
        <ul>
          <li><strong>Cena:</strong> {{ product.price }}</li>
          <li><strong>Dostępność:</strong> {% if product.available %}Dostępny{% else %}Niedostępny{% endif %}</li>
          <li><strong>Ilość na stanie:</strong> {{ product.stock_quantity }}</li>
          <li><strong>Magento SKU:</strong> {{ product.magento_sku }}</li>
        </ul>
        <div class="mt-4">
        <div class="input-group">
          <div class="input-group-prepend">
            <button class="btn btn-secondary" type="button" id="decrease-quantity-btn">-</button>
          </div>
          <input id="quantity-input" class="form-control quantity-input" value="1" min="1" max="{{ product.stock_quantity }}">
          <div class="input-group-append">
            <button class="btn btn-secondary" type="button" id="increase-quantity-btn">+</button>
          </div>
        </div>
        <div class="mt-4">
          <a href="{% url 'magento_integration_app:product-list' %}" class="btn btn-primary">Powrót do listy produktów</a>
          <button class="btn btn-success" id="add-to-cart-btn" data-product-sku="{{ product.magento_sku }}">Dodaj do koszyka</button>
        </div>
      </div>
    </div>
  </div>
</div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      // Obsługa kliknięcia przycisku "Dodaj do koszyka"
      $("#add-to-cart-btn").click(function() {
        var productSku = $(this).data("product-sku");
        var quantity = $("#quantity-input").val();

        // Wywołaj endpoint API do dodawania produktu do koszyka
        $.ajax({
          url: "{% url 'magento_integration_app:add-to-cart' %}",
          method: "POST",
          headers: {
            "X-CSRFToken": "{{ csrf_token }}"
          },
          data: {
            magento_sku: productSku,
            quantity: quantity
          },
          success: function(response) {
            // Obsłuż odpowiedź sukcesu
            console.log(response.success);
          },
          error: function(xhr, status, error) {
            // Obsłuż błąd
            console.error(xhr.responseText);
          }
        });
      });

      $("#decrease-quantity-btn").click(function() {
        var quantityInput = $("#quantity-input");
        var quantity = parseInt(quantityInput.val());

        if (quantity > 1) {
          quantityInput.val(quantity - 1);
        }
      });

      $("#increase-quantity-btn").click(function() {
        var quantityInput = $("#quantity-input");
        var quantity = parseInt(quantityInput.val());
        var stockQuantity = parseInt("{{ product.stock_quantity }}");


        if (quantity < stockQuantity) {
            quantityInput.val(quantity + 1);
          }
        });
      });
  </script>
{% endblock %}

magento_integration/magento_integration_app/templates/product_list.html
<!-- product_list.html -->
{% include 'base.html' %}

{% block content %}

  <div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {{ request.user }}
      {% for product in products %}
        <div class="col">
          <div class="card">
            <img src="" class="card-img-top" alt="{{ product.name }}">
            <div class="card-body">
              <h5 class="card-title">{{ product.name }}</h5>
              <p class="card-text">{{ product.description }}</p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Cena: {{ product.price }}</li>
                <li class="list-group-item">Dostępność: {% if product.available %}Dostępny{% else %}Niedostępny{% endif %}</li>
                <li class="list-group-item">Ilość na stanie: {{ product.stock_quantity }}</li>
              </ul>
            </div>
             <div class="card-footer">
              <a href="{% url 'magento_integration_app:product-detail' product.id %}" class="btn btn-primary">Przejdź do szczegółów</a>
              <button class="btn btn-success">Dodaj do koszyka</button>
            </div>
          </div>
        </div>
      {% empty %}
        <p>Brak produktów do wyświetlenia.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

magento_integration/magento_integration_app/templates/remove_from_cart.html
{% extends 'cart.html' %}

{% block content %}
  <div class="container">
    <h1>Usunięcie produktu z koszyka</h1>
    <p>Czy na pewno chcesz usunąć ten produkt z koszyka?</p>
    <form action="{% url 'magento_integration_app:delete-cart-item' item_id=item.id %}" method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Usuń</button>
    </form>
  </div>
{% endblock %}